### ISSUE TITLE
Data availability prior to 2000 + Frequency Change

### ISSUE THREAD

**Issue by KathyGCY** [TheEconomist/big-mac-data#14]
Dear Developers / Maintainers,
How are you today?

I'm writing to check if data before 2000 is available? Based on wikipedia it seems this index was created in 1986, but it would appear that the data on this repo starts in year 2000.

Also, it would appear that there seems to be a frequency change from annually 2000~2005 to semi-annually after 2006. How often is the data refreshed?

Thank you and have a wonderful day!
All the best,
Kathy Gao

**Comment by roxwillis** [comment]
Dear Kathy,

Thank you for your message. We have added our historical data which goes back to 1986, here:
https://github.com/TheEconomist/big-mac-data/blob/master/source-data/big-mac-historical-source-data.csv

As you point out the frequency of the data changes. Since 2012 we have run the index twice a year, prior to that we ran it at least once a year, sometimes twice. The countries included also varies.

Hope this answers your question. Thank you for your interest in _The Economist_.

Best,
Roxana
