### ISSUE TITLE
Reconciling IMF GDP PC data and the figures in the dataset

### ISSUE THREAD

**Issue by danielnjoo** [TheEconomist/big-mac-data#18]
Hi and thanks for the package!

You note that GDP PC ($) figures are taken from the IMF but there's no GDP data for most countries (50-70% of the 56 countries) in the dataset pre-July-2011, and consequently no `adj_price`, etc. I'd be interested in extending the data back to 2000 if possible. So I'd be curious why this wasn't possible with your original IMF source/dataset, since the data does exist.

I'd also be interested in which source you did use as I downloaded the IMF World Economic Outlook Database data from [datahub](https://datahub.io/core/imf-weo#resource-indicators) to try and do so myself. This database covers 55 of the 56 countries in the Big Mac dataset. Though observations are on a yearly basis, comparing the GDP PC ($) from this dataset versus the figures from the Big Mac dataset shows consistent variations:

![image](https://user-images.githubusercontent.com/16789604/95111718-7aa17580-0772-11eb-9eda-358e570414f5.png)

Plot above shows average proportional difference `(IMF_GDP-big_mac_GDP)/big_mac_GDP` when grouped by year and country where `big_mac_GDP` is the average of the two GDP figures if there are two in a given year.

Assuming the IMF dataset above is downloaded and saved as `values_csv.csv`, then the following code reproduces the plot above:

```
library(tidyverse)

big_mac_data <- readr::read_csv("big-mac-full-index.csv") %>% 
  janitor::clean_names()

IMF_data <- read_csv("values_csv.csv") %>% 
  filter(
    Indicator == "NGDPDPC", # this is the indicator code for GDP pc in $
    Country %in% unique(big_mac_data$iso_a3), 
    Year %in% 2000:2020
  ) 

GDP_data <- big_mac_data %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(iso_a3, year) %>% 
  summarize(big_mac_GDP = mean(gdp_dollar, na.rm=T)) %>% 
  inner_join(IMF_data, by=c("year"="Year", "iso_a3"="Country")) %>% 
  rename("IMF_GDP" = Value) 

GDP_data %>% 
  filter(!is.na(big_mac_GDP)) %>% 
  mutate(var = IMF_GDP-big_mac_GDP) %>% 
  group_by(year, iso_a3) %>% 
  summarize(prop = mean(var)/big_mac_GDP) %>% 
  ggplot(aes(iso_a3, prop)) + 
  geom_bar(stat = "identity") +
  labs(title="") +
  coord_flip() +
  facet_wrap(~year)
```

**Comment by futuraprime** [comment]
Hi Daniel, thanks for filing this. We corresponded separately by email, but for the benefit of anyone else who runs into this problem, I'll summarise the explanation here:

When we calculate the Big Mac index, we use the latest _non-estimated_ GDP figures they provide in the World Economic Outlook report (typically six to 12 months old). For example, we've just switched to the 2020 figures for the July 2021 release; we used the 2019 figures in January. (This got a little more complicated last year, as the IMF did not update their GDP figures in early 2020 due to uncertainty around covid.)

Further complicating matters is that the IMF revises its historical GDP figures over time, so the values for a country's GDP per capita in a given year which we used at publication may not match the values listed for that year in a future IMF report. For example, in the July 2020 Big Mac release, we reckoned New Zealand's GDP per capita at US$41,204 in 2018, based on the October 2019 World Economic Outlook's release (again, we used slightly older data than normal because of covid). The October 2020 release, however, pegged New Zealand's 2018 GDP as $42,603—quite a bit different.

We arre limited to the data available to us at publication. But if you are recalculating the adjusted index, it is reasonable to use the latest revisions from the IMF, and to use the years that correspond to the index (rather than lagging them).
